### ISSUE TITLE
Playwright有潜在的OOM链式崩溃风险

### ISSUE THREAD

**Issue by hsyhhssyy** [AmiyaBot/Amiya-Bot-core#3]
### 问题描述

我在k8s集群里跑amiyabot的时候，发现一个小问题，系统内存里驻留了大量的Chrome进程，观察运行情况，猜测是内存用尽，最后失去响应。

![image](https://user-images.githubusercontent.com/5977110/197080734-8417f9c9-1c3a-4ac9-b9b8-c0dd6b1807b3.png)

我检查了一下代码，怀疑是在playwright遇到错误的时候，你们忘记close page导致这个chrome就永远驻留内存了
因为各种机缘巧合，playwright出错就会导致一个驻留，日积月累就会渐渐占满内存

具体来说，在browserService.py的open_page函数里，如果执行page的函数抛出异常，就会导致这个page对象丢失，再也不会回收，这里建议是加一块finally来尝试执行page.close

### 复现

这个问题比较难以复现，因为你需要通过机缘巧合让playwright出错，最简单的办法就是发起一个cpu load，这样chrome就会因为没有cpu资源而超时，进而抛出错误。

### Amiya-Bot 版本

6.0.0

### 日志

```text
2022-10-21 07:46:37,955 [     Bot][   ERROR] Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/formdata.py", line 136, in _gen_form_data
    part = payload.get_payload(
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/payload.py", line 73, in get_payload
    return PAYLOAD_REGISTRY.get(data, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/payload.py", line 112, in get
    raise LookupError()
aiohttp.payload.LookupError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/amiyabot/network/httpRequests.py", line 26, in __handle_requests
    yield session, handler
  File "/usr/local/lib/python3.8/dist-packages/amiyabot/network/httpRequests.py", line 62, in upload
    async with session.post(interface, data=data) as res:
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/client.py", line 492, in _request
    req = self._request_class(
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/client_reqrep.py", line 313, in __init__
    self.update_body_from_data(data)
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/client_reqrep.py", line 507, in update_body_from_data
    body = body()
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/formdata.py", line 168, in __call__
    return self._gen_form_data()
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/formdata.py", line 147, in _gen_form_data
    raise TypeError(
TypeError: Can not serialize value type: <class 'NoneType'>
 headers: {'Content-Type': 'application/octet-stream'}
 value: None
2022-10-21 07:46:37,959 [     Bot][   ERROR] handler error: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/amiyabot/log/manager.py", line 100, in catch
    yield
  File "/usr/local/lib/python3.8/dist-packages/amiyabot/__init__.py", line 46, in __message_handler
    await message_handler(self, event, message)
  File "/usr/local/lib/python3.8/dist-packages/amiyabot/handler/messageHandler.py", line 61, in message_handler
    reply = await handler.action(data)
  File "/usr/local/lib/python3.8/dist-packages/amiyabot/handler/messageHandlerDefine.py", line 134, in action
    return await self.function(data)
  File "/amiyabot/functions/about.py", line 20, in _
    reply = await data.wait(Chain(data).markdown(content))
  File "/usr/local/lib/python3.8/dist-packages/amiyabot/builtin/message.py", line 88, in wait
    await self.instance.send_chain_message(reply)
  File "/usr/local/lib/python3.8/dist-packages/amiyabot/adapters/mirai/__init__.py", line 98, in send_chain_message
    reply, voice_list = await build_message_send(self.api, chain)
  File "/usr/local/lib/python3.8/dist-packages/amiyabot/adapters/mirai/builder.py", line 55, in build_message_send
    'imageId': await get_image_id(api, await item.create_html_image(), chain.data.message_type)
  File "/usr/local/lib/python3.8/dist-packages/amiyabot/adapters/mirai/builder.py", line 66, in get_image_id
    return await http.upload_image(target, msg_type)
  File "/usr/local/lib/python3.8/dist-packages/amiyabot/adapters/mirai/api.py", line 48, in upload_image
    if 'imageId' in res:
TypeError: argument of type 'NoneType' is not iterable
2022-10-21 07:50:17,071 [     Bot][   ERROR] html convert error: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/amiyabot/log/manager.py", line 100, in catch
    yield
  File "/usr/local/lib/python3.8/dist-packages/amiyabot/builtin/messageChain/element.py", line 58, in create_html_image
    page = await basic_browser_service.open_page(self.template,
  File "/usr/local/lib/python3.8/dist-packages/amiyabot/builtin/lib/browserService.py", line 51, in open_page
    await page.goto(url)
  File "/usr/local/lib/python3.8/dist-packages/playwright/async_api/_generated.py", line 7601, in goto
    await self._async(
  File "/usr/local/lib/python3.8/dist-packages/playwright/_impl/_page.py", line 493, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "/usr/local/lib/python3.8/dist-packages/playwright/_impl/_frame.py", line 122, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "/usr/local/lib/python3.8/dist-packages/playwright/_impl/_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "/usr/local/lib/python3.8/dist-packages/playwright/_impl/_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
navigating to "file:////amiyabot/plugins/amiyabot-arknights-operator-1_4/template/operatorInfo.html", waiting until "load"
```

### 补充信息

日志不好找了，这是当时timeout的错误，验证了我的猜测

**Comment by vivien8261** [comment]
#6
