### ISSUE TITLE
ValueError: 'not' is not a valid parameter name

### ISSUE THREAD

**Issue by Rst307** [AmiyaBot/Amiya-Bot-core#83]
import asyncio

from amiyabot import Chain, AmiyaBot, Message

bot = AmiyaBot(appid='x', token='x', private=True)

@bot.on_message(keywords='hello')
async def _(data: Message):
    return Chain(data).text(f'hello, {data.nickname}')

asyncio.run(bot.start())

**Comment by vivien8261** [comment]
你好，可以提供详细的报错信息吗

**Comment by Rst307** [comment]
Traceback (most recent call last):
  File "C:\Users\mcroc\paytowin_test\lifeti,e\test.py", line 3, in <module>
    from amiyabot import AmiyaBot, Message, Chain
  File "C:\Users\mcroc\paytowin_test\lifeti,e\.venv\Lib\site-packages\amiyabot\__init__.py", line 21, in <module>
    from amiyabot.network.httpServer import HttpServer
  File "C:\Users\mcroc\paytowin_test\lifeti,e\.venv\Lib\site-packages\amiyabot\network\httpServer\__init__.py", line 2, in <module>
    from fastapi import FastAPI, Request, Response
  File "C:\Users\mcroc\paytowin_test\lifeti,e\.venv\Lib\site-packages\fastapi\__init__.py", line 7, in <module>
    from .applications import FastAPI as FastAPI
  File "C:\Users\mcroc\paytowin_test\lifeti,e\.venv\Lib\site-packages\fastapi\applications.py", line 15, in <module>
    from fastapi import routing
  File "C:\Users\mcroc\paytowin_test\lifeti,e\.venv\Lib\site-packages\fastapi\routing.py", line 23, in <module>
    from fastapi.dependencies.models import Dependant
  File "C:\Users\mcroc\paytowin_test\lifeti,e\.venv\Lib\site-packages\fastapi\dependencies\models.py", line 3, in <module>
    from fastapi.security.base import SecurityBase
  File "C:\Users\mcroc\paytowin_test\lifeti,e\.venv\Lib\site-packages\fastapi\security\__init__.py", line 1, in <module>
    from .api_key import APIKeyCookie as APIKeyCookie
  File "C:\Users\mcroc\paytowin_test\lifeti,e\.venv\Lib\site-packages\fastapi\security\api_key.py", line 3, in <module>
    from fastapi.openapi.models import APIKey, APIKeyIn
  File "C:\Users\mcroc\paytowin_test\lifeti,e\.venv\Lib\site-packages\fastapi\openapi\models.py", line 103, in <module>
    class Schema(BaseModel):
  File "C:\Users\mcroc\paytowin_test\lifeti,e\.venv\Lib\site-packages\pydantic\main.py", line 292, in __new__
    cls.__signature__ = ClassAttribute('__signature__', generate_model_signature(cls.__init__, fields, config))
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mcroc\paytowin_test\lifeti,e\.venv\Lib\site-packages\pydantic\utils.py", line 258, in generate_model_signature
    merged_params[param_name] = Parameter(
                                ^^^^^^^^^^
  File "C:\Users\mcroc\AppData\Local\Programs\Python\Python311\Lib\inspect.py", line 2722, in __init__
    raise ValueError('{!r} is not a valid parameter name'.format(name))
ValueError: 'not' is not a valid parameter name

**Comment by A1KESH1** [comment]
遇到同样问题，环境如下：
WinServer 2019 DC
Pip 22.3.1 
Python 3.11.3

报错信息：
C:\Users\Administrator\Desktop\python\qq_channel_bot\venv\Scripts\python.exe C:\Users\Administrator\Desktop\python\qq_channel_bot\bot_hello.py 
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\python\qq_channel_bot\bot_hello.py", line 3, in <module>
    from amiyabot import AmiyaBot, Message, Chain
  File "C:\Users\Administrator\Desktop\python\qq_channel_bot\venv\Lib\site-packages\amiyabot\__init__.py", line 21, in <module>
    from amiyabot.network.httpServer import HttpServer
  File "C:\Users\Administrator\Desktop\python\qq_channel_bot\venv\Lib\site-packages\amiyabot\network\httpServer\__init__.py", line 2, in <module>
    from fastapi import FastAPI, Request, Response
  File "C:\Users\Administrator\Desktop\python\qq_channel_bot\venv\Lib\site-packages\fastapi\__init__.py", line 7, in <module>
    from .applications import FastAPI as FastAPI
  File "C:\Users\Administrator\Desktop\python\qq_channel_bot\venv\Lib\site-packages\fastapi\applications.py", line 15, in <module>
    from fastapi import routing
  File "C:\Users\Administrator\Desktop\python\qq_channel_bot\venv\Lib\site-packages\fastapi\routing.py", line 23, in <module>
    from fastapi.dependencies.models import Dependant
  File "C:\Users\Administrator\Desktop\python\qq_channel_bot\venv\Lib\site-packages\fastapi\dependencies\models.py", line 3, in <module>
    from fastapi.security.base import SecurityBase
  File "C:\Users\Administrator\Desktop\python\qq_channel_bot\venv\Lib\site-packages\fastapi\security\__init__.py", line 1, in <module>
    from .api_key import APIKeyCookie as APIKeyCookie
  File "C:\Users\Administrator\Desktop\python\qq_channel_bot\venv\Lib\site-packages\fastapi\security\api_key.py", line 3, in <module>
    from fastapi.openapi.models import APIKey, APIKeyIn
  File "C:\Users\Administrator\Desktop\python\qq_channel_bot\venv\Lib\site-packages\fastapi\openapi\models.py", line 103, in <module>
    class Schema(BaseModel):
  File "C:\Users\Administrator\Desktop\python\qq_channel_bot\venv\Lib\site-packages\pydantic\main.py", line 292, in __new__
    cls.__signature__ = ClassAttribute('__signature__', generate_model_signature(cls.__init__, fields, config))
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\python\qq_channel_bot\venv\Lib\site-packages\pydantic\utils.py", line 258, in generate_model_signature
    merged_params[param_name] = Parameter(
                                ^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\inspect.py", line 2722, in __init__
    raise ValueError('{!r} is not a valid parameter name'.format(name))
ValueError: 'not' is not a valid parameter name

Process finished with exit code 1

**Comment by A1KESH1** [comment]
已解决https://github.com/tiangolo/fastapi/issues/5048#issuecomment-1229183881
